.TH "/Users/peterjanku/SourcesCpp/ArkArena/tests/ImageBuffer_test.cc" 3 "Fri Feb 18 2022" "Version v0.0.1" "ArkArena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/peterjanku/SourcesCpp/ArkArena/tests/ImageBuffer_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./tools/ImageBuffer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (ImageBufferTest, InitialConditions)"
.br
.ti -1c
.RI "\fBTEST\fP (ImageBufferTest, SimplePushFetch)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (ImageBufferTest, InitialConditions)"
Test of initial state of the buffer 
.SS "TEST (ImageBufferTest, SimplePushFetch)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ArkArena from the source code\&.
