.TH "md___users_peterjanku__sources_cpp__ark_arena__c_o_n_t_r_i_b_u_t_i_o_n" 3 "Fri Feb 18 2022" "Version v0.0.1" "ArkArena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_peterjanku__sources_cpp__ark_arena__c_o_n_t_r_i_b_u_t_i_o_n \- Contributing to KilobotArena project 
Every contribution to this project is welcome\&. In order to keep this project clean and easy to maintain, please follow the rules and recommendations described in this document\&.
.SH "Issues"
.PP
Feel free to submit issues and feature requests as well as any bug found in this project into our \fCdiscusions\&.\fP
.SH "Contributing"
.PP
In general, we follow the 'fork-and-pull' Git workflow\&.
.PP
.IP "1." 4
\fBFork\fP the repo on GitHub
.IP "2." 4
\fBClone\fP the project to your own machine
.IP "3." 4
\fBCommit\fP changes to your own branch
.IP "4." 4
\fBPush\fP your work back up to your fork
.IP "5." 4
Submit a \fBPull request\fP so that we can review your changes
.PP
.PP
NOTE: Be sure to merge the latest from 'upstream' before making a pull request!
.PP
\fI\fBPlease take care bout folowing recommendations:\fP\fP
.IP "\(bu" 2
keep commit messages meaningful
.IP "  \(bu" 4
don't use messages like 'some minore changes', 'imporved functionality', 'banch of changes', 'my fist commit', etc\&.
.PP

.IP "\(bu" 2
keep your commits clear
.IP "  \(bu" 4
if it is possible don't mix new features, improvements and bud-fixing in one commit
.PP

.IP "\(bu" 2
\fBcomment your code\fP
.IP "  \(bu" 4
use Doxygen comment style
.IP "  \(bu" 4
keep comments meaningful
.IP "  \(bu" 4
if it is possible place comments into \&.cpp files
.PP

.IP "\(bu" 2
when you create a pull request describe the changed is pullrequest comment 
.br

.IP "\(bu" 2
\fBif it is possible create unit test for each new unit\fP 
.PP

